### ISSUE TITLE
emq_auth_mysql load fail

### ISSUE THREAD

**Issue by jhaoheng** [emqtt/emq-docker#26]
Make sure you read and understand http://emqtt.io/docs/v2/index.html.
Use one of the two templates below and delete the rest.

- [X] BUG REPORT
- [ ] FEATURE REQUEST

-------------------------------------------------------------------------------
> BUG REPORT

### Expected behavior
Make a mariadb to connect EMQ, and make EMQ enable 'emq_auth_mysql' plugin

### Actual behavior
> error

```
load plugin error: {emq_auth_mysql,
                    {bad_return,
                     {{emq_auth_mysql_app,start,[normal,[]]},
                      {'EXIT',
                       {{badmatch,
                         {error,
                          {shutdown,
                           {failed_to_start_child,emq_auth_mysql,
                            {shutdown,
                             {failed_to_start_child,worker_sup,
                              {shutdown,
                               {failed_to_start_child,
                                {worker,1},
                                {{badmatch,{error,econnrefused}},
                                 [{mysql,init,1,
                                   [{file,"src/mysql.erl"},{line,484}]},
                                  {gen_server,init_it,6,
                                   [{file,"gen_server.erl"},{line,328}]},
                                  {proc_lib,init_p_do_apply,3,
                                   [{file,"proc_lib.erl"},
                                    {line,247}]}]}}}}}}}}},
                        [{emq_auth_mysql_app,start,2,
                          [{file,"src/emq_auth_mysql_app.erl"},{line,33}]},
                         {application_master,start_it_old,4,
                          [{file,"application_master.erl"},{line,273}]}]}}}}}
``` 

### Test code
> db schema ref EMQ supplier

```
version: "3.2"
services:
  mariadb:
    image: mariadb
    container_name: mariadb
    ports:
      - 6612:3306/tcp
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./database/schema.sql:/docker-entrypoint-initdb.d/base_schema.sql
      
  mqtt_broker:
    image: emqttd:2.3-rc.2
    ports:
      - 18083:18083/tcp # dashboard
      - 1883:1883/tcp   # MQTT TCP port
      - 8883:8883/tcp   # MQTT TCP TLS/SSL port
      - 8083:8083/tcp   # HTTP and WebSocket port
      - 8084:8084/tcp   # HTTPS and WSS port
      - 8080:8080/tcp   # mgmt API port
    container_name: mqtt_broker
    depends_on:
      - mariadb
    links:
      - mariadb
    # domainname: 
    # hostname: 
    user: root
    environment:
      # configure : https://github.com/emqtt/emqttd/blob/master/etc/emq.conf
      # - EMQ_HOST=
      - EMQ_WAIT_TIME=5
      - EMQ_ADMIN_PASSWORD=admin
      # - EMQ_LOG__CONSOLE=console
      - EMQ_MQTT__ALLOW_ANONYMOUS=true
      - EMQ_MQTT__MAX_PACKET_SIZE=64KB
      - EMQ_LOADED_PLUGINS="emq_auth_mysql, emq_recon, emq_modules, emq_retainer, emq_dashboard"

      # #mysql parameters
      - EMQ_AUTH__MYSQL__SERVER=mariadb:6612
      # - EMQ_AUTH__MYSQL__POOL=8
      - EMQ_AUTH__MYSQL__USERNAME=root
      - EMQ_AUTH__MYSQL__PASSWORD=root
      - EMQ_AUTH__MYSQL__DATABASE=mqtt_demo
      - EMQ_AUTH__MYSQL__AUTH_QUERY=SELECT password FROM mqtt_user WHERE username = '%u' LIMIT 1
      - EMQ_AUTH__MYSQL__PASSWORD_HASH=plain #plain, md5, sha, sha256, bcrypt
      - EMQ_AUTH__MYSQL__SUPER_QUERY=select is_superuser from mqtt_user where username = '%u' limit 1
      - EMQ_AUTH__MYSQL__ACL_QUERY=select allow, ipaddr, username, clientid, access, topic from mqtt_acl where ipaddr = '%a' or username = '%u' or username = '$all' or clientid = '%c'
      - EMQ_AUTH__MYSQL__ACL_QUERY=select allow, ipaddr, username, clientid, access, topic from mqtt_acl where ipaddr = '%a' or username = '%u' or username = '$all' or clientid = '%c'
      - EMQ_AUTH__MYSQL__ACL_NOMATCH=deny
```

### EMQ version
2.3-rc.2

### Docker version
Docker version 17.09.0-ce, build afdb6d4

### System

> What system do you use?
osx

-------------------------------------------------------------------------------
