### ISSUE TITLE
Environment variable to configure container failed when value include "http://" like

### ISSUE THREAD

**Issue by eastpav** [emqtt/emq-docker#29]
when I use docker-compose  yml configure container like this:
```
version: '2.0'

services:
    mongo:
        image: emqttd:master
        hostname: emqttd
        ports:
            - "18083:18083"
            - "1883:1883"
            - "8083:8083" 
            - "8883:8883"
        environment:
            - EMQ_CLUSTER__DISCOVERY=k8s
            - EMQ_CLUSTER__K8S__APISERVER=http://172.16.1.225:8080
            - EMQ_CLUSTER__K8S__SERVICE_NAME=ekka
            - EMQ_CLUSTER__K8S__ADDRESS_TYPE=ip
            - EMQ_CLUSTER__K8S__APP_NAME=ekka
```
It cause set option error, the error line in start.sh is:
```
sed -r -i "s/(^#*\s*)($VAR_NAME)\s*=\s*(.*)/\2 = $(eval echo \$$VAR_FULL_NAME)/g" $CONFIG
```
it replaced as 
```
sed -r -i "s/(^#*\s*)(cluster.k8s.apiserver)\s*=\s*(.*)/\2 = http://172.16.1.225:8080/g"
```
The format is wrong in sed, “http://“ must be "http:\\/\\/"，so  can not use $eval directly. 
It works when I modified start.sh like this：
```
if [[ ! -z "$(cat $CONFIG |grep -E "^(^|^#*|^#*\s*)$VAR_NAME")" ]]; then
            echo "emq.conf: $VAR_NAME=$(eval echo \$$VAR_FULL_NAME)"
            VAR_VALUE=$(eval echo \$$VAR_FULL_NAME)
            VAR_VALUE_R=${VAR_VALUE//\//\\\/}
            sed -r -i "s/(^#*\s*)($VAR_NAME)\s*=\s*(.*)/\2 = $VAR_VALUE_R/g" $CONFIG
```
Changes must be done in all the lines include sed with eval.
