### ISSUE TITLE
Retained messages persistence

### ISSUE THREAD

**Issue by miks** [emqtt/emq-docker#64]
Are there any recommended way how to make retained messages persistent between EMQ deployments?
For me it looks like there is no use for EMQ in Kubernetes because:
1) by default kubernetes will mount `/opt/emqttd/data/mnesia` as root:root.
That lead be to rather hacky attempt to solve this by:
```
      securityContext:
        runAsUser: 0
        fsGroup: 1000
      containers:
      - name: emqtt
        image: private.registry/emqttd-docker:v2.3.9
        command: ["/bin/sh", "-c"]
        args:
          - chown emqtt:emqtt /opt/emqttd/data/mnesia && su -l emqtt -p -c /opt/emqttd/start.sh
        ports:
```
2) even with correct permissions for `/opt/emqttd/data/mnesia` EMQ will just start with new node nam e on each restart:
```
# ls /opt/emqttd/data/mnesia/
emqtt-56f55b4794-xfzcq@10.42.0.71
emqtt-644b575465-6s44d@10.42.0.68
emqtt-78ccff4f74-sstmt@10.42.0.70
emqtt-644b575465-6h8mj@10.42.0.69
emqtt-6669477d59-mgrqt@10.42.0.72
```
setting EMQ_NAME, EMQ_HOST or EMQ_NODE__NAME make no effect to use persistent mnesia path
